42ity/fty-email

install.xml, src/fty-email.conf, src/fty_email.cc
Solution: add install.xml model to install additional files via
deb/rpm packages
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
=> Problem: third party files not installed

src/fty-email.cfg.in
Solution: Change them to new ones.
=> Problem: Config file of fty-email contains old paths.

src/fty_email_server.cc
Solution: Do not filter messages for existing alerts
=> Problem: alert is resolved but email are sent forever

include/fty_email.h
=> Problem: new parameter is needed

src/fty_email_server.cc
Solution: state file disabled for one of the actors
=> Problem: one state file overwrites the other

src/alert.h, src/fty_email_server.cc
Solution: update code, follow new api
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
=> Problem: agent doesn't compile after fty_proto update

.gitignore, src/fty_email_server.cc
=> Problem: we need want to use new fty-proto

src/fty_email.cc, src/fty_sendmail.cc
Solution: make older OSes happier and slightly optimize CLI argument processing.
=> Problem: portability of this component can be improved

packaging/redhat/fty-email.spec, project.xml
Solution: Rename & regenerate
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
=> Problem: Tag spec_name is now redhat_name

src/alert.cc, src/fty_email.cc, src/fty_email_server.cc, src/fty_sendmail.cc
Solution: clean up the codebase
=> Problem: too many typos in sources of tests

src/fty_email_server.cc
Solution: fty_email_server.cc : fix create_smtp_server() to use a standardly created temporary config file instead of a hardcoded name in potentially missing or inaccessible subdir
See also issue #25 and PR #27 for related details
When reviewing, in particular, mind the FIXME comments...
=> Problem: create_smtp_server() uses an "src/smtp.cfg" filename

src/elementlist.cc, src/elementlist.h, src/emailconfiguration.cc, src/fty_email_server.cc
=> Problem: we want to see asset friendly name in emails not DB name

README.md
Solution: Add one, describe current state and capabilities.
=> Problem: README missing.

README.md, src/emailconfiguration.cc, src/emailconfiguration.h, src/fty-email.cfg.in, src/fty_email.cc, src/fty_email_server.cc
Solution: Update SENDMAIL_ALERT request and reply, update e-mail generation, remove asset cache, update the tests.
=> Problem: Protocol SENDMAIL_ALERT has been modified.

README.md
=> Problem: README is out of date.

src/fty-email.cfg.in
Solution: added missing sms template
=> Problem: email crashes due to missing template

src/fty_email_server.cc
=> Problem: exception handled incorrectly

fty-device-scan
Solution: Force numeric walks
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
=> Problem: We want pure numeric SNMP walks

src/email.cc, src/fty_sendmail.cc
=> Problem: namespace of process functions changed

src/fty_email_server.cc
=> (S/S) Problem: We need to use C++ wrapper.

src/fty-email.cfg.in, src/fty_email.cc
Solution: Make it possible.
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
=> (S/M) Problem: Fty-email cannot use non-default language.

src/fty_email_server.cc
Solution: Escape the error message here, transform it into JSON in REST API.
=> (S/M) Problem: We have to change error behaviour of email_* REST API calls.

src/.valgrind.supp, src/email.cc, src/emailconfiguration.cc, src/emailconfiguration.h, src/fty_email_server.cc
Signed-off-by: Millieret, Xavier <XavierMillieret@Eaton.com>
=> Adding Ip adrr in the email body

src/emailconfiguration.cc
Signed-off-by: Millieret, Xavier <XavierMillieret@Eaton.com>
=> Fixing issue with Ip address (2 times wrote in the email)

src/fty-email.cfg.in
Signed-off-by: MimiXav <XavierMillieret@eaton.com>
=> Removing space to be compliant with SRR augeas lens

src/email.cc
Solution: Fix it, and add some debug traces
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
=> Problem: Encryption config is not taken into account

src/fty_email_server.cc
* make error msg more human readable
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
=> IPMPROG-1468 - send email: make error msg more human readable
